apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-sync
spec:
  provider: azure
  secretObjects:
    - secretName: firevault-k8s-secret
      type: Opaque
      data:
        - objectName: azure-storage-account-name
          key: AZURE_STORAGE_ACCOUNT_NAME
        - objectName: azure-storage-account-key
          key: AZURE_STORAGE_ACCOUNT_KEY
        - objectName: azure-container-name
          key: AZURE_CONTAINER_NAME
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "24dc778a-2d9a-4dbf-9e5c-c4712510fd34"
    keyvaultName: "firevault-secrets"
    tenantId: "34cc7ab5-fd16-446f-bd35-2d04775d2de1"
    objects: |
      array:
        - |
          objectName: azure-storage-account-name
          objectType: secret
        - |
          objectName: azure-storage-account-key
          objectType: secret
        - |
          objectName: azure-container-name
          objectType: secret
