name: Build, Test, and Deploy to AKS

on:
  push:
    branches: ["main"]
    paths:
      - 'src/azure-sa/**'
      - 'deployment.yaml'
      - 'service.yaml'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "firevaultregistry"
  CONTAINER_NAME: "firevault-app"
  RESOURCE_GROUP: "aks-resource-group"
  CLUSTER_NAME: "firevault-cluster"
  SOURCE_ROOT: "src/azure-sa"

permissions:
  id-token: write
  contents: read

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install and Test
        working-directory: ${{ env.SOURCE_ROOT }}
        run: |
          npm ci
          npm run lint
          npm test

  buildImage:
    needs: [quality-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2 
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }} 

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SOURCE_ROOT }}
          file: ${{ env.SOURCE_ROOT }}/Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy:
    needs: [buildImage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set K8s Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            deployment.yaml
            service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}