name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terraform.yml"
      - "**.tf"
      - "deployment.yaml"
      - "!**.md"

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for Checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      # These 4 env vars are all the Azurerm provider needs for OIDC
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # -input=false ensures the pipeline fails with an error instead of hanging
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false